### ISSUE TITLE
Please add validation to RadioBrowserServer class

### ISSUE THREAD

**Issue by haecksenwerk** [phranck/RadioBrowserKit#2]
Currently, the domain "fr1.api.radio-browser.info" is down, so the RadioBrowser API does not work whenever this hostname is chosen from the server list

**Comment by phranck** [comment]
Hey @haecksenwerk,

sorry for my late reply. I will look into it.

**Comment by haecksenwerk** [comment]
Hi @phranck,

No problem. In the meantime, I've cobbled together a few radio browser API functions that are sufficient for my app. Your code was a helpful template. So, thanks a lot for your work 😊

As for fetching a radio-browser server, I came up with this solution:


```swift
final class Server {
    
    let URL_HTTP = "http://all.api.radio-browser.info/json"
    let URL_HTTPS = "https://de1.api.radio-browser.info/json"
    
    private struct Server: Codable {
        public var ip: String
        public var name: String
    }
    
    public func fetchBaseUrls () async throws -> [String] {
        guard var url = URL(string: URL_HTTPS) else {
            throw RadioBrowserError.invalidUrl
        }
        
        var servers: [String] = []
        url = url.appendingPathComponent("/servers")
        
        do {
            let (data, _) = try await URLSession.shared.data(from: url)
            
            if let response = try? JSONDecoder().decode([Server].self, from: data) {
                servers = response.map({ server -> String in
                    return "https://\(server.name)/json"  })
            }
        } catch  {
            throw RadioBrowserError.getBaseUrl(error: error)
        }
        
        return servers
    }
}

```

**Comment by phranck** [comment]
Great! If you think some of your code might interesting to others, please don't hesitate to open a pull request. 😃

**Comment by haecksenwerk** [comment]
Well, I think my code isn't because I am still too much at the Swift rookie level. I guess I just posted it because I was happy that I got it working at all 💪😅
